# Creating Forward pass in neural network

In [58]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def relu(x):
    return np.maximum(0, x)



# Defining the neural network architecture

In [59]:
input_size = 2 # it means that there are two inputs
hidden_size = 6 # it means there are three hidden layer
output_size = 2 # as there are two inputs there will be two outputs

# generating random input data

In [60]:
input_data = np.random.randn(1, input_size)
print(input_data)

[[1.95963161 1.03174217]]


# Initialize random weights

- weights can't be negative.

In [61]:
weights_input_to_hidden = np.random.randn(input_size, hidden_size)
weights_hidden_to_output = np.random.randn(hidden_size, output_size)

In [62]:
print("weight_of_input_layer:\n", weights_input_to_hidden)
print("weights_hidden_output:\n",weights_hidden_to_output)

weight_of_input_layer:
 [[-0.72892983 -1.21092759  0.52577761 -0.90171757  0.94203508 -1.15501073]
 [-0.21707728  0.32891622  0.47896457 -0.77536388  1.70111818  0.62134914]]
weights_hidden_output:
 [[-0.1010274  -1.30837866]
 [ 1.2622504  -0.29981904]
 [ 1.37057355  0.58926297]
 [-2.06863578  0.87240129]
 [-0.1200127  -0.99585772]
 [-0.36237476 -0.34763484]]


# Forward pass

In [63]:
hidden_layer_input = np.dot(input_data, weights_input_to_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_input = np.dot(hidden_layer_output, weights_hidden_to_output)
output_layer_output = relu(output_layer_input)

In [64]:
print("hidden_layer_input: \n",hidden_layer_input)
print("hidden_layer_output:\n",hidden_layer_output)

hidden_layer_input: 
 [[-1.65240172 -2.03361526  1.52449837 -2.56700986  3.60115709 -1.62232342]]
hidden_layer_output:
 [[0.16078461 0.11571847 0.82119993 0.07129203 0.97343295 0.16488469]]


In [65]:
print("output_layer_input:\n",output_layer_input)
print("output_layer_output:\n",output_layer_output)

output_layer_input:
 [[ 0.93128534 -0.72568416]]
output_layer_output:
 [[0.93128534 0.        ]]
